# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new internal Build to Firebase App Tester"
  lane :internal do
            build_android_app(task: "assembleInternalRelease")

            firebase_app_distribution(
                app: "1:513153680889:android:9275847f99e1001e",
                groups: "beta-testers",
                release_notes: changelog_from_git_commits(pretty: '%h %s'),
                firebase_cli_path: "/usr/local/bin/firebase"
            )
        end

  desc "Submit a new internal Build to Play Store"
  lane :internal_play_store do
    gradle(task: "clean assembleInternalRelease")
    upload_to_play_store(track: 'internal')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new production version to Google Play"
  lane :deploy do
    gradle(task: "clean assemblePlaystoreRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
